/* ========================================================
   Huzur Vakti - Yeni Özellik Veri Setleri (content.js)
   Bu dosya mevcut data.js'i değiştirmez, sadece yeni veriler ekler.
   ======================================================== */

/* ══════════ GÜNÜN HADİSİ (40+ Hadis) ══════════ */
const HADITHS = [
  { ar: "إِنَّمَا الْأَعْمَالُ بِالنِّيَّاتِ", text: "Ameller (yapılan işler) ancak niyetlere göre değerlenir. Herkese niyet ettiği şeyin karşılığı vardır.", source: "Buhârî, Müslim" },
  { text: "Kolaylaştırınız, güçleştirmeyiniz. Müjdeleyiniz, nefret ettirmeyiniz.", source: "Buhârî, İlim 11" },
  { text: "Müslüman, elinden ve dilinden diğer Müslümanların zarar görmediği kimsedir.", source: "Buhârî, Îmân 4" },
  { text: "Sizin en hayırlınız, Kur'an'ı öğrenen ve öğretendir.", source: "Buhârî, Fedâilü'l-Kur'ân 21" },
  { text: "Temizlik imanın yarısıdır.", source: "Müslim, Tahâret 1" },
  { text: "Kişi sevdiği ile beraberdir.", source: "Buhârî, Edeb 96" },
  { text: "Küçüklerimize merhamet etmeyen, büyüklerimize saygı göstermeyen bizden değildir.", source: "Tirmizî, Birr 15" },
  { text: "Mümin bir delikten iki kez ısırılmaz.", source: "Buhârî, Edeb 83" },
  { text: "Allah katında en sevimli amel, az da olsa devamlı olanıdır.", source: "Buhârî, Îmân 32" },
  { text: "Güzel söz sadakadır.", source: "Buhârî, Cihâd 72" },
  { text: "İnsanların en hayırlısı, insanlara en faydalı olanıdır.", source: "Beyhakî" },
  { text: "Veren el, alan elden üstündür.", source: "Buhârî, Zekât 18" },
  { text: "Allah'a ve ahiret gününe iman eden ya hayır söylesin ya da sussun.", source: "Buhârî, Edeb 31" },
  { text: "Cennet annelerin ayakları altındadır.", source: "Nesâî, Cihâd 6" },
  { text: "Sizin en hayırlınız, ailesine karşı en iyi olanınızdır.", source: "Tirmizî, Menâkıb 63" },
  { text: "Zenginlik, mal çokluğu değildir. Asıl zenginlik gönül tokluğudur.", source: "Buhârî, Rikâk 15" },
  { text: "Komşusu açken tok yatan bizden değildir.", source: "Hâkim, Müstedrek" },
  { text: "Bir kötülük gördüğünüzde onu elinizle, gücünüz yetmezse dilinizle, ona da gücünüz yetmezse kalbinizle düzeltmeye çalışın.", source: "Müslim, Îmân 78" },
  { text: "Kim bir mümini bir sıkıntıdan kurtarırsa, Allah da onu kıyamet günü sıkıntılarından kurtarır.", source: "Müslim, Zikr 38" },
  { text: "Gülümsemen kardeşinin yüzüne karşı bir sadakadır.", source: "Tirmizî, Birr 36" },
  { text: "Dua ibadetin özüdür.", source: "Tirmizî, Deavât 1" },
  { text: "Allah sizin suretlerinize ve mallarınıza değil, kalplerinize ve amellerinize bakar.", source: "Müslim, Birr 34" },
  { text: "Öfkelendiğinde susan kurtuldu.", source: "Ahmed b. Hanbel" },
  { text: "İki nimet vardır ki insanların çoğu onları değerlendirmede aldanmıştır: Sağlık ve boş vakit.", source: "Buhârî, Rikâk 1" },
  { text: "Kim Allah için bir cami yaparsa, Allah da ona cennette bir ev yapar.", source: "Buhârî, Salât 65" },
  { text: "Namazın anahtarı temizliktir.", source: "Ebû Dâvûd, Tahâret 31" },
  { text: "Ramazan ayı girip de günahları bağışlanmadan çıkan kimse rahmetten uzak olsun.", source: "Tirmizî, Deavât 100" },
  { text: "Sadaka malı eksiltmez.", source: "Müslim, Birr 69" },
  { text: "Kolayca kızmayan ve çabuk sakinleşen kişi en hayırlınızdır.", source: "Tirmizî, Fiten 26" },
  { text: "İlim öğrenmek her Müslümana farzdır.", source: "İbn Mâce, Mukaddime 17" },
  { text: "Cömert insan Allah'a yakın, cennete yakın, insanlara yakın ve cehennemden uzaktır.", source: "Tirmizî, Birr 40" },
  { text: "Kim bir hayra vesile olursa, o hayrı yapan gibi sevap alır.", source: "Müslim, İmâre 133" },
  { text: "Yumuşaklık nerede bulunursa orayı süsler, nereden çekilip alınırsa orayı çirkinleştirir.", source: "Müslim, Birr 78" },
  { text: "Mümin müminin aynasıdır.", source: "Ebû Dâvûd, Edeb 49" },
  { text: "En üstün cihad, zalim sultanın karşısında hakkı söylemektir.", source: "Ebû Dâvûd, Melâhim 17" },
  { text: "Kim bir yetimin başını okşarsa, elinin dokunduğu her kıl sayısınca ona sevap yazılır.", source: "Ahmed b. Hanbel" },
  { text: "Allah'ım! Faydasız ilimden, huşû duymayan kalpten, doymayan nefisten Sana sığınırım.", source: "Müslim, Zikr 73" },
  { text: "Din nasihattir (samimiyettir).", source: "Müslim, Îmân 95" },
  { text: "İnsanlara teşekkür etmeyen, Allah'a da şükretmez.", source: "Tirmizî, Birr 35" },
  { text: "Sabır, aydınlıktır.", source: "Müslim, Tahâret 1" },
  { text: "Rızkının bol olmasını isteyen, akrabası ile ilişkisini sürdürsün.", source: "Buhârî, Edeb 12" }
];

/* ══════════ ESMAÜL HÜSNA (99 İsim) ══════════ */
const ESMA_UL_HUSNA = [
  { no: 1, ar: "الرَّحْمَنُ", tr: "Er-Rahmân", meaning: "Dünyada bütün mahlûkata merhamet eden, şefkat gösteren, ihsan eden." },
  { no: 2, ar: "الرَّحِيمُ", tr: "Er-Rahîm", meaning: "Ahirette yalnız müminlere sonsuz merhamet ve ikram eden." },
  { no: 3, ar: "الْمَلِكُ", tr: "El-Melik", meaning: "Bütün kâinatın gerçek sahibi ve mutlak hükümdarı." },
  { no: 4, ar: "الْقُدُّوسُ", tr: "El-Kuddûs", meaning: "Her türlü eksiklik ve ayıptan uzak, tertemiz olan." },
  { no: 5, ar: "السَّلاَمُ", tr: "Es-Selâm", meaning: "Her türlü tehlikeden selamete çıkaran, esenlik veren." },
  { no: 6, ar: "الْمُؤْمِنُ", tr: "El-Mü'min", meaning: "Güven veren, emin kılan, kalplere iman veren." },
  { no: 7, ar: "الْمُهَيْمِنُ", tr: "El-Müheymin", meaning: "Her şeyi görüp gözeten, koruyup denetleyen." },
  { no: 8, ar: "الْعَزِيزُ", tr: "El-Azîz", meaning: "İzzet sahibi, mağlup edilemeyen, her şeye galip olan." },
  { no: 9, ar: "الْجَبَّارُ", tr: "El-Cebbâr", meaning: "Dilediğini zorla yaptırmaya muktedir, azametli olan." },
  { no: 10, ar: "الْمُتَكَبِّرُ", tr: "El-Mütekebbir", meaning: "Büyüklükte eşi olmayan, azamet ve ululuk sahibi." },
  { no: 11, ar: "الْخَالِقُ", tr: "El-Hâlık", meaning: "Her şeyi yoktan yaratan, takdir eden." },
  { no: 12, ar: "الْبَارِئُ", tr: "El-Bârî", meaning: "Her şeyi kusursuz ve uyumlu yaratan." },
  { no: 13, ar: "الْمُصَوِّرُ", tr: "El-Musavvir", meaning: "Her şeye şekil ve suret veren." },
  { no: 14, ar: "الْغَفَّارُ", tr: "El-Gaffâr", meaning: "Günahları çokça örten ve bağışlayan." },
  { no: 15, ar: "الْقَهَّارُ", tr: "El-Kahhâr", meaning: "Her şeye galip gelen, kahretmeye gücü yeten." },
  { no: 16, ar: "الْوَهَّابُ", tr: "El-Vehhâb", meaning: "Karşılıksız çokça veren, bağışlayan." },
  { no: 17, ar: "الرَّزَّاقُ", tr: "Er-Rezzâk", meaning: "Bütün mahlûkatın rızkını veren." },
  { no: 18, ar: "الْفَتَّاحُ", tr: "El-Fettâh", meaning: "Her türlü zorluğu açan, hayır kapılarını aralayan." },
  { no: 19, ar: "اَلْعَلِيمُ", tr: "El-Alîm", meaning: "Her şeyi en ince ayrıntısına kadar bilen." },
  { no: 20, ar: "الْقَابِضُ", tr: "El-Kâbıd", meaning: "Dilediğine rızkı daraltan, ruhları alan." },
  { no: 21, ar: "الْبَاسِطُ", tr: "El-Bâsıt", meaning: "Dilediğine rızkı genişleten, açan." },
  { no: 22, ar: "الْخَافِضُ", tr: "El-Hâfıd", meaning: "Dilediğini alçaltan, dereceleri düşüren." },
  { no: 23, ar: "الرَّافِعُ", tr: "Er-Râfi'", meaning: "Dilediğini yücelten, dereceleri yükselten." },
  { no: 24, ar: "الْمُعِزُّ", tr: "El-Muizz", meaning: "Dilediğine izzet ve şeref veren." },
  { no: 25, ar: "الْمُذِلُّ", tr: "El-Müzill", meaning: "Dilediğini zillete düşüren, alçaltan." },
  { no: 26, ar: "السَّمِيعُ", tr: "Es-Semî'", meaning: "Her şeyi işiten, duaları duyan." },
  { no: 27, ar: "الْبَصِيرُ", tr: "El-Basîr", meaning: "Her şeyi gören, gizli açık her şeyden haberdar." },
  { no: 28, ar: "الْحَكَمُ", tr: "El-Hakem", meaning: "Mutlak hüküm veren, son kararı veren hâkim." },
  { no: 29, ar: "الْعَدْلُ", tr: "El-Adl", meaning: "Mutlak adalet sahibi, asla haksızlık etmeyen." },
  { no: 30, ar: "اللَّطِيفُ", tr: "El-Latîf", meaning: "En ince işlerin bütün inceliklerini bilen, lütuf sahibi." },
  { no: 31, ar: "الْخَبِيرُ", tr: "El-Habîr", meaning: "Her şeyin iç yüzünden, gizliliklerinden haberdar olan." },
  { no: 32, ar: "الْحَلِيمُ", tr: "El-Halîm", meaning: "Cezada acele etmeyen, yumuşak davranan." },
  { no: 33, ar: "الْعَظِيمُ", tr: "El-Azîm", meaning: "Azamet ve büyüklük sahibi, ululuk sahibi." },
  { no: 34, ar: "الْغَفُورُ", tr: "El-Gafûr", meaning: "Günahları çok bağışlayan, mağfireti bol olan." },
  { no: 35, ar: "الشَّكُورُ", tr: "Eş-Şekûr", meaning: "Az iyiliğe çok mükâfat veren, şükre karşılık veren." },
  { no: 36, ar: "الْعَلِيُّ", tr: "El-Aliyy", meaning: "Yüceler yücesi, her şeyden yüksek olan." },
  { no: 37, ar: "الْكَبِيرُ", tr: "El-Kebîr", meaning: "Büyüklükte kendisine sınır olmayan, en büyük." },
  { no: 38, ar: "الْحَفِيظُ", tr: "El-Hafîz", meaning: "Her şeyi koruyan, muhafaza eden." },
  { no: 39, ar: "الْمُقِيتُ", tr: "El-Mukît", meaning: "Her canlının gıdasını, rızkını veren." },
  { no: 40, ar: "الْحَسِيبُ", tr: "El-Hasîb", meaning: "Herkesin hesabını gören, kullarına yeten." },
  { no: 41, ar: "الْجَلِيلُ", tr: "El-Celîl", meaning: "Celal ve azamet sahibi, ulu olan." },
  { no: 42, ar: "الْكَرِيمُ", tr: "El-Kerîm", meaning: "Sonsuz cömertlik ve kerem sahibi." },
  { no: 43, ar: "الرَّقِيبُ", tr: "Er-Rakîb", meaning: "Her şeyi gözetleyen, kontrol eden." },
  { no: 44, ar: "الْمُجِيبُ", tr: "El-Mucîb", meaning: "Dualara ve isteklere karşılık veren." },
  { no: 45, ar: "الْوَاسِعُ", tr: "El-Vâsi'", meaning: "İlmi ve rahmeti her şeyi kuşatan, geniş olan." },
  { no: 46, ar: "الْحَكِيمُ", tr: "El-Hakîm", meaning: "Her işi hikmetli olan, sonsuz hikmet sahibi." },
  { no: 47, ar: "الْوَدُودُ", tr: "El-Vedûd", meaning: "Kullarını çok seven, sevilmeye layık olan." },
  { no: 48, ar: "الْمَجِيدُ", tr: "El-Mecîd", meaning: "Şanı yüce, şeref ve azamet sahibi." },
  { no: 49, ar: "الْبَاعِثُ", tr: "El-Bâis", meaning: "Ölüleri dirilten, peygamber gönderen." },
  { no: 50, ar: "الشَّهِيدُ", tr: "Eş-Şehîd", meaning: "Her zaman ve her yerde hazır ve nazır olan, her şeye şahit." },
  { no: 51, ar: "الْحَقُّ", tr: "El-Hakk", meaning: "Varlığı hiç değişmeyen, mutlak gerçek olan." },
  { no: 52, ar: "الْوَكِيلُ", tr: "El-Vekîl", meaning: "Kendisine tevekkül edenlerin işini en iyi gören." },
  { no: 53, ar: "الْقَوِيُّ", tr: "El-Kaviyy", meaning: "Sonsuz kudret ve güç sahibi." },
  { no: 54, ar: "الْمَتِينُ", tr: "El-Metîn", meaning: "Çok sağlam, kuvvetli ve dayanıklı olan." },
  { no: 55, ar: "الْوَلِيُّ", tr: "El-Veliyy", meaning: "Müminlerin dostu, onlara yardım eden." },
  { no: 56, ar: "الْحَمِيدُ", tr: "El-Hamîd", meaning: "Her türlü övgüye layık olan, övülen." },
  { no: 57, ar: "الْمُحْصِي", tr: "El-Muhsî", meaning: "Her şeyin sayısını tek tek bilen." },
  { no: 58, ar: "الْمُبْدِئُ", tr: "El-Mübdî", meaning: "Her şeyi ilk baştan, örneksiz yaratan." },
  { no: 59, ar: "الْمُعِيدُ", tr: "El-Muîd", meaning: "Yarattıklarını yok edip tekrar dirilten." },
  { no: 60, ar: "الْمُحْيِي", tr: "El-Muhyî", meaning: "Can veren, dirilten, hayat bahşeden." },
  { no: 61, ar: "اَلْمُمِيتُ", tr: "El-Mümît", meaning: "Her canlıya ölümü takdir eden, öldüren." },
  { no: 62, ar: "الْحَيُّ", tr: "El-Hayy", meaning: "Ezelî ve ebedî hayat sahibi, diri olan." },
  { no: 63, ar: "الْقَيُّومُ", tr: "El-Kayyûm", meaning: "Her şeyi ayakta tutan, varlığı kendinden olan." },
  { no: 64, ar: "الْوَاجِدُ", tr: "El-Vâcid", meaning: "İstediğini istediği anda bulan, hiçbir şeye muhtaç olmayan." },
  { no: 65, ar: "الْمَاجِدُ", tr: "El-Mâcid", meaning: "Şanı ve keremi büyük, yüce olan." },
  { no: 66, ar: "الْوَاحِدُ", tr: "El-Vâhid", meaning: "Zatında, sıfatlarında tek olan, ortağı bulunmayan." },
  { no: 67, ar: "اَلْأَحَدُ", tr: "El-Ehad", meaning: "Bölünmez, parçalanmaz, mutlak bir olan." },
  { no: 68, ar: "الصَّمَدُ", tr: "Es-Samed", meaning: "Hiçbir şeye muhtaç olmayan, her şey Kendisine muhtaç olan." },
  { no: 69, ar: "الْقَادِرُ", tr: "El-Kâdir", meaning: "Her şeye gücü yeten, kudret sahibi." },
  { no: 70, ar: "الْمُقْتَدِرُ", tr: "El-Muktedir", meaning: "Kudreti her şeye yeten, dilediğini yapan." },
  { no: 71, ar: "الْمُقَدِّمُ", tr: "El-Mukaddim", meaning: "Dilediğini öne alan, ileri geçiren." },
  { no: 72, ar: "الْمُؤَخِّرُ", tr: "El-Muahhir", meaning: "Dilediğini geriye bırakan, erteleyen." },
  { no: 73, ar: "الأوَّلُ", tr: "El-Evvel", meaning: "Başlangıcı olmayan, her şeyden önce var olan." },
  { no: 74, ar: "الآخِرُ", tr: "El-Âhir", meaning: "Sonu olmayan, her şey yok olduktan sonra bâki kalan." },
  { no: 75, ar: "الظَّاهِرُ", tr: "Ez-Zâhir", meaning: "Varlığı sayısız delil ile aşikâr olan." },
  { no: 76, ar: "الْبَاطِنُ", tr: "El-Bâtın", meaning: "Akılların idrak edemeyeceği, gizli olan." },
  { no: 77, ar: "الْوَالِي", tr: "El-Vâlî", meaning: "Bütün kâinatı yöneten, idare eden." },
  { no: 78, ar: "الْمُتَعَالِي", tr: "El-Müteâlî", meaning: "Aklın alabileceği her şeyden yüce olan." },
  { no: 79, ar: "الْبَرُّ", tr: "El-Berr", meaning: "Kullarına karşı iyiliği ve ihsanı bol olan." },
  { no: 80, ar: "التَّوَّابُ", tr: "Et-Tevvâb", meaning: "Tövbeleri çokça kabul eden, günahları bağışlayan." },
  { no: 81, ar: "الْمُنْتَقِمُ", tr: "El-Müntekim", meaning: "Zalimlere adaletiyle hak ettikleri cezayı veren." },
  { no: 82, ar: "العَفُوُّ", tr: "El-Afüvv", meaning: "Günahları affeden, silip yok eden." },
  { no: 83, ar: "الرَّؤُوفُ", tr: "Er-Raûf", meaning: "Çok merhametli, çok şefkatli olan." },
  { no: 84, ar: "مَالِكُ الْمُلْكِ", tr: "Mâlikü'l-Mülk", meaning: "Mülkün gerçek sahibi, dilediği gibi tasarruf eden." },
  { no: 85, ar: "ذُوالْجَلاَلِ وَالإكْرَامِ", tr: "Zü'l-Celâli ve'l-İkrâm", meaning: "Celal, azamet, lütuf ve ikram sahibi." },
  { no: 86, ar: "الْمُقْسِطُ", tr: "El-Muksit", meaning: "Bütün işlerini denk ve adaletli yapan." },
  { no: 87, ar: "الْجَامِعُ", tr: "El-Câmi'", meaning: "Dilediğini dilediği zaman toplayan, bir araya getiren." },
  { no: 88, ar: "الْغَنِيُّ", tr: "El-Ganî", meaning: "Hiçbir şeye ihtiyacı olmayan, zengin olan." },
  { no: 89, ar: "الْمُغْنِي", tr: "El-Muğnî", meaning: "Dilediğini zengin eden, ihtiyacını gideren." },
  { no: 90, ar: "اَلْمَانِعُ", tr: "El-Mâni'", meaning: "Dilemediği şeylere engel olan, koruyan." },
  { no: 91, ar: "الضَّارُّ", tr: "Ed-Dârr", meaning: "Hikmetiyle zarar ve elem verebilen." },
  { no: 92, ar: "النَّافِعُ", tr: "En-Nâfi'", meaning: "Fayda ve menfaat veren, hayır ulaştıran." },
  { no: 93, ar: "النُّورُ", tr: "En-Nûr", meaning: "Âlemleri nurlandıran, dilediğine hidayet nuru veren." },
  { no: 94, ar: "الْهَادِي", tr: "El-Hâdî", meaning: "Hidayet veren, doğru yola ileten." },
  { no: 95, ar: "الْبَدِيعُ", tr: "El-Bedî'", meaning: "Örneksiz, benzersiz güzellikte yaratan." },
  { no: 96, ar: "اَلْبَاقِي", tr: "El-Bâkî", meaning: "Varlığının sonu olmayan, ebedî kalan." },
  { no: 97, ar: "الْوَارِثُ", tr: "El-Vâris", meaning: "Her şeyin gerçek sahibi, her şey yok olunca kalan." },
  { no: 98, ar: "الرَّشِيدُ", tr: "Er-Reşîd", meaning: "Bütün işleri doğru ve yerli yerince olan, doğruya ulaştıran." },
  { no: 99, ar: "الصَّبُورُ", tr: "Es-Sabûr", meaning: "Çok sabırlı olan, cezayı erteleyip acele etmeyen." }
];

/* ══════════ DUA ÖĞRENME ══════════ */
const DUA_LEARN = [
  {
    title: "Sübhaneke Duası",
    arabic: "سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ وَتَبَارَكَ اسْمُكَ وَتَعَالَى جَدُّكَ وَلَا إِلَهَ غَيْرُكَ",
    okunusu: "Sübhânekellâhümme ve bi-hamdik, ve tebârekesmük, ve teâlâ ceddük, ve lâ ilâhe ğayruk.",
    turkish: "Allah'ım! Seni her türlü noksanlıktan tenzih eder ve hamd ile överim. Senin adın mübarektir, şanın yücedir. Senden başka ilah yoktur.",
    note: "Namaza başlarken, iftitah tekbirinden sonra okunur."
  },
  {
    title: "Ettehiyyâtü Duası",
    arabic: "التَّحِيَّاتُ لِلَّهِ وَالصَّلَوَاتُ وَالطَّيِّبَاتُ السَّلَامُ عَلَيْكَ أَيُّهَا النَّبِيُّ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ السَّلَامُ عَلَيْنَا وَعَلَى عِبَادِ اللَّهِ الصَّالِحِينَ أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ",
    okunusu: "Ettehiyyâtü lillâhi vessalevâtü vettayyibât. Esselâmü aleyke eyyühen-nebiyyü ve rahmetullâhi ve berakâtüh. Esselâmü aleynâ ve alâ ibâdillâhis-sâlihîn. Eşhedü en lâ ilâhe illallâh ve eşhedü enne Muhammeden abdühû ve rasûlüh.",
    turkish: "Her türlü hürmet, ibadet ve güzellikler Allah'adır. Ey Peygamber! Allah'ın selamı, rahmeti ve bereketi senin üzerine olsun. Selam bizim ve Allah'ın salih kullarının üzerine olsun. Şahitlik ederim ki Allah'tan başka ilah yoktur ve yine şahitlik ederim ki Muhammed O'nun kulu ve elçisidir.",
    note: "Her oturuşta (ka'de) okunur."
  },
  {
    title: "Salli - Bârik Duaları",
    arabic: "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا صَلَّيْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ ۝ اللَّهُمَّ بَارِكْ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا بَارَكْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ",
    okunusu: "Allâhümme salli alâ Muhammedin ve alâ âli Muhammed, kemâ salleyte alâ İbrâhîme ve alâ âli İbrâhîm, inneke hamîdün mecîd. Allâhümme bârik alâ Muhammedin ve alâ âli Muhammed, kemâ bârekte alâ İbrâhîme ve alâ âli İbrâhîm, inneke hamîdün mecîd.",
    turkish: "Allah'ım! İbrahim'e ve ailesine rahmet ettiğin gibi Muhammed'e ve ailesine de rahmet et. Şüphesiz sen övülmeye layıksın, şanı yücesin. Allah'ım! İbrahim'e ve ailesine bereket verdiğin gibi Muhammed'e ve ailesine de bereket ver. Şüphesiz sen övülmeye layıksın, şanı yücesin.",
    note: "Son oturuşta Ettehiyyâtü'den sonra okunur."
  },
  {
    title: "Kunut Duaları",
    arabic: "اللَّهُمَّ إِنَّا نَسْتَعِينُكَ وَنَسْتَغْفِرُكَ وَنَسْتَهْدِيكَ وَنُؤْمِنُ بِكَ وَنَتُوبُ إِلَيْكَ وَنَتَوَكَّلُ عَلَيْكَ وَنُثْنِي عَلَيْكَ الْخَيْرَ كُلَّهُ نَشْكُرُكَ وَلَا نَكْفُرُكَ وَنَخْلَعُ وَنَتْرُكُ مَنْ يَفْجُرُكَ",
    okunusu: "Allâhümme innâ nesteînüke ve nestağfirüke ve nestehdîk. Ve nü'minü bike ve netûbü ileyk. Ve netevekkelü aleyke ve nüsnî aleykel-hayra küllehû neşkürüke ve lâ nekfürüke ve nahleu ve netrükü mey yefcürük.",
    turkish: "Allah'ım! Senden yardım isteriz, günahlarımızı bağışlamanı isteriz, razı olduğun şeylere hidayet etmeni isteriz. Sana inanırız, sana tövbe ederiz. Sana güveniriz. Bütün hayırları senden bilerek seni överiz. Sana şükrederiz, nankörlük etmeyiz. Sana isyan edeni bırakırız.",
    note: "Vitir namazının 3. rekâtında okunur."
  },
  {
    title: "Âyetel Kürsî",
    arabic: "اللَّهُ لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ مَنْ ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلَّا بِإِذْنِهِ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ وَلَا يُحِيطُونَ بِشَيْءٍ مِنْ عِلْمِهِ إِلَّا بِمَا شَاءَ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ وَلَا يَئُودُهُ حِفْظُهُمَا وَهُوَ الْعَلِيُّ الْعَظِيمُ",
    okunusu: "Allâhü lâ ilâhe illâ hüvel-hayyül-kayyûm. Lâ te'huzühû sinetün ve lâ nevm. Lehû mâ fis-semâvâti ve mâ fil-ard. Menzellezî yeşfeu indehû illâ bi-iznih. Ya'lemü mâ beyne eydîhim ve mâ halfehüm. Ve lâ yühîtûne bi-şey'in min ilmihî illâ bimâ şâ'. Vesia kürsiyyühüs-semâvâti vel-ard. Ve lâ yeûdühû hıfzuhümâ ve hüvel-aliyyül-azîm.",
    turkish: "Allah, kendisinden başka hiçbir ilah olmayandır. Diridir, kayyumdur. O'nu ne bir uyuklama ne de uyku tutar. Göklerdeki ve yerdeki her şey O'nundur. İzni olmaksızın O'nun katında kim şefaat edebilir? O, kullarının önlerindekini ve arkalarındakini bilir. Onlar O'nun ilminden, ancak dilediği kadarını kavrayabilirler. O'nun kürsüsü bütün gökleri ve yeri kaplar. Onları koruyup gözetmek O'na güç gelmez. O yücedir, büyüktür.",
    note: "Bakara suresi 255. ayet. En faziletli ayetlerdendir."
  },
  {
    title: "Âmenerrasûlü (Bakara 285-286)",
    arabic: "آمَنَ الرَّسُولُ بِمَا أُنْزِلَ إِلَيْهِ مِنْ رَبِّهِ وَالْمُؤْمِنُونَ كُلٌّ آمَنَ بِاللَّهِ وَمَلَائِكَتِهِ وَكُتُبِهِ وَرُسُلِهِ لَا نُفَرِّقُ بَيْنَ أَحَدٍ مِنْ رُسُلِهِ وَقَالُوا سَمِعْنَا وَأَطَعْنَا غُفْرَانَكَ رَبَّنَا وَإِلَيْكَ الْمَصِيرُ",
    okunusu: "Âmener-rasûlü bimâ ünzile ileyhi min rabbihî vel-mü'minûn. Küllün âmene billâhi ve melâiketihî ve kütübihî ve rusülih. Lâ nüferriku beyne ehadin min rusülih. Ve kâlû semi'nâ ve eta'nâ ğufrâneke rabbenâ ve ileykel-masîr.",
    turkish: "Peygamber, Rabbinden kendisine indirilene iman etti, müminler de. Hepsi Allah'a, meleklerine, kitaplarına ve peygamberlerine iman ettiler. 'O'nun peygamberlerinden hiçbirini diğerinden ayırmayız' ve 'İşittik ve itaat ettik. Ey Rabbimiz! Senden bağışlama dileriz, dönüş yalnız sanadır' dediler.",
    note: "Bakara suresinin son iki ayetidir. Yatmadan önce okunması tavsiye edilir."
  }
];

/* ══════════ SABAH / AKŞAM EZKÂRI ══════════ */
const EZKAR_SABAH = [
  { title: "Âyetel Kürsî", arabic: "اللَّهُ لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ...", okunusu: "Allâhü lâ ilâhe illâ hüvel-hayyül-kayyûm...", turkish: "Sabah okuyan akşama kadar korunur.", count: 1 },
  { title: "İhlâs Sûresi", arabic: "قُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُنْ لَهُ كُفُوًا أَحَدٌ", okunusu: "Kul hüvellâhü ehad. Allâhüs-samed. Lem yelid ve lem yûled. Ve lem yekün lehû küfüven ehad.", turkish: "Kur'an'ın üçte birine denktir.", count: 3 },
  { title: "Felâk Sûresi", arabic: "قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ...", okunusu: "Kul eûzü bi-rabbil-felak...", turkish: "Şerlerden Allah'a sığınma suresidir.", count: 3 },
  { title: "Nâs Sûresi", arabic: "قُلْ أَعُوذُ بِرَبِّ النَّاسِ...", okunusu: "Kul eûzü bi-rabbin-nâs...", turkish: "Vesveseden Allah'a sığınma suresidir.", count: 3 },
  { title: "Sabah Tesbihi", arabic: "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ", okunusu: "Asbahnâ ve asbahal-mülkü lillâh.", turkish: "Sabaha erdik, mülk Allah'ındır.", count: 1 },
  { title: "Seyyidü'l-İstiğfar", arabic: "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ خَلَقْتَنِي وَأَنَا عَبْدُكَ", okunusu: "Allâhümme ente rabbî lâ ilâhe illâ ente halaktenî ve ene abdük...", turkish: "İstiğfarların efendisidir. Okuyan cennetliktir.", count: 1 },
  { title: "Tesbih", arabic: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ", okunusu: "Sübhânallâhi ve bi-hamdih.", turkish: "Allah'ı hamd ile tesbih ederim.", count: 100 },
  { title: "Salavât", arabic: "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ", okunusu: "Allâhümme salli alâ Muhammed.", turkish: "Allah'ım Muhammed'e salât eyle.", count: 10 },
  { title: "Tevhid", arabic: "لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ", okunusu: "Lâ ilâhe illallâhü vahdehû lâ şerîke leh...", turkish: "Allah birdir, ortağı yoktur.", count: 10 }
];

const EZKAR_AKSAM = [
  { title: "Âyetel Kürsî", arabic: "اللَّهُ لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ...", okunusu: "Allâhü lâ ilâhe illâ hüvel-hayyül-kayyûm...", turkish: "Akşam okuyan sabaha kadar korunur.", count: 1 },
  { title: "İhlâs Sûresi", arabic: "قُلْ هُوَ اللَّهُ أَحَدٌ...", okunusu: "Kul hüvellâhü ehad...", turkish: "Kur'an'ın üçte birine denktir.", count: 3 },
  { title: "Felâk Sûresi", arabic: "قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ...", okunusu: "Kul eûzü bi-rabbil-felak...", turkish: "Şerlerden Allah'a sığınma suresidir.", count: 3 },
  { title: "Nâs Sûresi", arabic: "قُلْ أَعُوذُ بِرَبِّ النَّاسِ...", okunusu: "Kul eûzü bi-rabbin-nâs...", turkish: "Vesveseden Allah'a sığınma suresidir.", count: 3 },
  { title: "Akşam Tesbihi", arabic: "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ", okunusu: "Emseynâ ve emsel-mülkü lillâh.", turkish: "Akşama erdik, mülk Allah'ındır.", count: 1 },
  { title: "Sığınma Duası", arabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ", okunusu: "Eûzü bi-kelimâtillâhit-tâmmâti min şerri mâ halak.", turkish: "Allah'ın tam kelimeleriyle yarattıklarının şerrinden sığınırım.", count: 3 },
  { title: "Tesbih", arabic: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ", okunusu: "Sübhânallâhi ve bi-hamdih.", turkish: "Allah'ı hamd ile tesbih ederim.", count: 100 },
  { title: "Salavât", arabic: "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ", okunusu: "Allâhümme salli alâ Muhammed.", turkish: "Allah'ım Muhammed'e salât eyle.", count: 10 },
  { title: "İstiğfar", arabic: "أَسْتَغْفِرُ اللَّهَ الْعَظِيمَ", okunusu: "Estağfirullâhel-azîm.", turkish: "Yüce Allah'tan bağışlanma dilerim.", count: 33 }
];

/* ══════════ GÜNLÜK DUALAR ══════════ */
const GUNLUK_DUALAR = [
  { title: "Yemekten Önce", arabic: "بِسْمِ اللَّهِ", okunusu: "Bismillâh.", turkish: "Allah'ın adıyla (başlarım).", tag: "yemek" },
  { title: "Yemekten Sonra", arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ", okunusu: "Elhamdü lillâhillezî et'amenâ ve sekânâ ve cealenâ müslimîn.", turkish: "Bizi doyuran, içiren ve Müslümanlardan kılan Allah'a hamd olsun.", tag: "yemek" },
  { title: "Uyumadan Önce", arabic: "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا", okunusu: "Bismike Allâhümme emûtü ve ahyâ.", turkish: "Allah'ım! Senin adınla ölür ve dirilirim.", tag: "uyku" },
  { title: "Uyanınca", arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ", okunusu: "Elhamdü lillâhillezî ahyânâ ba'de mâ emâtenâ ve ileyhin-nüşûr.", turkish: "Bizi öldürdükten sonra dirilten Allah'a hamd olsun. Dönüş O'nadır.", tag: "uyku" },
  { title: "Tuvalete Girerken", arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ", okunusu: "Allâhümme innî eûzü bike minel-hubüsi vel-habâis.", turkish: "Allah'ım! Erkek ve dişi şeytanların şerrinden sana sığınırım.", tag: "tuvalet" },
  { title: "Tuvaletten Çıkarken", arabic: "غُفْرَانَكَ", okunusu: "Ğufrâneke.", turkish: "Ya Rabbi! Senden bağışlanma dilerim.", tag: "tuvalet" },
  { title: "Eve Girerken", arabic: "بِسْمِ اللَّهِ وَلَجْنَا وَبِسْمِ اللَّهِ خَرَجْنَا وَعَلَى رَبِّنَا تَوَكَّلْنَا", okunusu: "Bismillâhi velecnâ ve bismillâhi haracnâ ve alâ rabbinâ tevekkelnâ.", turkish: "Allah'ın adıyla girer, Allah'ın adıyla çıkarız ve Rabbimize güveniriz.", tag: "ev" },
  { title: "Evden Çıkarken", arabic: "بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ", okunusu: "Bismillâhi tevekkeltü alâllâhi ve lâ havle ve lâ kuvvete illâ billâh.", turkish: "Allah'ın adıyla, Allah'a tevekkül ettim. Güç ve kuvvet ancak Allah'tandır.", tag: "ev" },
  { title: "Yolculuğa Çıkarken", arabic: "سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ", okunusu: "Sübhânellezî sahhara lenâ hâzâ ve mâ künnâ lehû mukrinîn.", turkish: "Bunu bizim hizmetimize veren Allah'ı tesbih ederim. Buna bizim gücümüz yetmezdi.", tag: "yolculuk" },
  { title: "Abdestten Sonra", arabic: "أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ", okunusu: "Eşhedü en lâ ilâhe illallâh ve eşhedü enne Muhammeden abdühû ve rasûlüh.", turkish: "Şahitlik ederim ki Allah'tan başka ilah yoktur ve Muhammed O'nun kulu ve elçisidir.", tag: "abdest" },
  { title: "Camiye Girerken", arabic: "اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ", okunusu: "Allâhümmeftah lî ebvâbe rahmetik.", turkish: "Allah'ım! Bana rahmet kapılarını aç.", tag: "cami" },
  { title: "Camiden Çıkarken", arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ", okunusu: "Allâhümme innî es'elüke min fadlik.", turkish: "Allah'ım! Senden lütfunu isterim.", tag: "cami" },
  { title: "Aynaya Bakınca", arabic: "اللَّهُمَّ كَمَا حَسَّنْتَ خَلْقِي فَحَسِّنْ خُلُقِي", okunusu: "Allâhümme kemâ hassente halkî fe-hassin hulukî.", turkish: "Allah'ım! Yaratılışımı güzel yaptığın gibi ahlakımı da güzelleştir.", tag: "ayna" },
  { title: "Nazara Karşı", arabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّةِ مِنْ كُلِّ شَيْطَانٍ وَهَامَّةٍ وَمِنْ كُلِّ عَيْنٍ لَامَّةٍ", okunusu: "Eûzü bi-kelimâtillâhit-tâmmeti min külli şeytânin ve hâmmetin ve min külli aynin lâmmeh.", turkish: "Her türlü şeytandan, zararlıdan ve kem gözden Allah'ın tam kelimelerine sığınırım.", tag: "nazar" },
  { title: "Sıkıntı Anında", arabic: "لَا إِلَهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ", okunusu: "Lâ ilâhe illâ ente sübhâneke innî küntü minez-zâlimîn.", turkish: "Senden başka ilah yoktur. Seni tenzih ederim. Gerçekten ben zalimlerden oldum.", tag: "sıkıntı" },
  { title: "Hastalık Anında", arabic: "أَذْهِبِ الْبَأْسَ رَبَّ النَّاسِ وَاشْفِ أَنْتَ الشَّافِي", okunusu: "Ezhibil-be'se rabben-nâsi veşfi entel-şâfî.", turkish: "Ey insanların Rabbi! Hastalığı gider, şifa ver. Şifa veren yalnız sensin.", tag: "hastalık" },
  { title: "Rızık İçin", arabic: "اللَّهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ", okunusu: "Allâhümmekfinî bi-helâlike an harâmik, ve ağninî bi-fadlike ammen sivâk.", turkish: "Allah'ım! Helalinle yetindirip haramına muhtaç etme; lütfunla beni senden başkasına muhtaç etme.", tag: "rızık" },
  { title: "İşe Başlarken", arabic: "بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ", okunusu: "Bismillâhirrahmânirrahîm.", turkish: "Rahman ve Rahim olan Allah'ın adıyla.", tag: "iş" }
];

/* ══════════ ÖNEMLİ SURELER (Hızlı Erişim) ══════════ */
const ONEMLI_SURELER = [
  { id: 36, name: "Yâsîn", fazilet: "Kur'an'ın kalbidir. Ölülerin ve dirilerin üzerine okunur, huzur ve mağfiret vesilesidir." },
  { id: 67, name: "Mülk (Tebâreke)", fazilet: "Kabir azabına engel olur; okuyanı ölene kadar korur ve şefaat eder." },
  { id: 18, name: "Kehf", fazilet: "Cuma günü okuyana iki cuma arası nur olur. Deccal fitnesinden korur." },
  { id: 56, name: "Vâkıa", fazilet: "Fakirlik korkusuna karşı okunur; her gece okuyana fakirlik dokunmaz." },
  { id: 55, name: "Rahmân", fazilet: "Kur'an'ın gelini; Allah'ın nimetlerini hatırlatan şükür suresidir." },
  { id: 1, name: "Fâtiha", fazilet: "Namazın direği, her rekâtta okunan; şifa ve dua suresidir." },
  { id: 112, name: "İhlâs", fazilet: "Tevhidin özü; üç kez okunması Kur'an'ın üçte birine denktir." },
  { id: 113, name: "Felâk", fazilet: "Dış şerlerden, büyü ve kötülüklerden korunma suresidir." },
  { id: 114, name: "Nâs", fazilet: "İç vesveseden, cin ve insan şerrinden korunma suresidir." },
  { id: 48, name: "Fetih", fazilet: "Zafer, feth ve müjde suresidir; okuyana kolaylık vesiledir." },
  { id: 78, name: "Nebe' (Amme)", fazilet: "Ahiret ve kıyamet hallerini anlatan uyarıcı suredir." },
  { id: 2, name: "Bakara", fazilet: "İçinde Âyetel Kürsî ve Âmenerrasûlü bulunur; şeytan girmeyen ev suresidir." }
];

/* ══════════ HİCRİ TAKVİM - KANDİL VE ÖNEMLİ GÜNLER (2026) ══════════ */
const KANDIL_GUNLERI = [
  { name: "Regâip Kandili", date: "2026-01-15", type: "kandil", desc: "Üç ayların ilk cuma gecesi. Rahmet ve mağfiret gecesidir." },
  { name: "Miraç Kandili", date: "2026-01-25", type: "kandil", desc: "Peygamberimizin Miraç'a yükseldiği gece. Beş vakit namazın farz kılındığı gecedir." },
  { name: "Berat Kandili", date: "2026-02-13", type: "kandil", desc: "Şaban ayının 15. gecesi. Kulların bir yıllık amellerinin arz edildiği af gecesidir." },
  { name: "Ramazan Başlangıcı", date: "2026-02-28", type: "bayram", desc: "On bir ayın sultanı Ramazan-ı Şerif'in başlangıcı." },
  { name: "Kadir Gecesi", date: "2026-03-25", type: "kandil", desc: "Bin aydan hayırlı gece. Kur'an'ın indirilmeye başladığı en faziletli gecedir." },
  { name: "Ramazan Bayramı", date: "2026-03-30", type: "bayram", desc: "Ramazan orucunun tamamlanmasıyla kutlanan bayram (arefe: 29 Mart)." },
  { name: "Kurban Bayramı", date: "2026-06-06", type: "bayram", desc: "Hac ibadetinin yapıldığı, kurban kesilen bayram (arefe: 5 Haziran)." },
  { name: "Hicrî Yılbaşı (1448)", date: "2026-06-26", type: "onemli", desc: "Muharrem ayının başlangıcı, yeni hicri yılın ilk günü." },
  { name: "Aşure Günü", date: "2026-07-05", type: "onemli", desc: "Muharrem ayının 10. günü. Birçok peygamberin kurtuluşuna vesile olan mübarek gün." },
  { name: "Mevlid Kandili", date: "2026-08-25", type: "kandil", desc: "Peygamber Efendimizin (s.a.v.) dünyaya teşrif ettiği gece." }
];

/* ══════════ CUMA MESAJLARI ══════════ */
const CUMA_MESAJLARI = [
  "Cuma; kalplerin arındığı, duaların kabul olduğu berekelli gündür. Hayırlı Cumalar. 🕌",
  "Rabbim bu mübarek Cuma hürmetine gönüllerinizi ferah, dualarınızı makbul eylesin. Hayırlı Cumalar. 🤲",
  "Bir Cuma sabahı daha... Kalbiniz huzurla, gönlünüz imanla dolsun. Hayırlı Cumalar. 🌸",
  "Salât ve selamların en güzeli Efendimize olsun. Bu Cuma rahmet olsun üzerinize. Hayırlı Cumalar. 🕌",
  "Duaların göklere yükseldiği bu güzel günde adınız hayırla anılsın. Hayırlı Cumalar. ✨",
  "Cuma; bereketin, rahmetin ve mağfiretin günüdür. Allah dualarınızı kabul etsin. Hayırlı Cumalar. 🤲",
  "Gönlünüzden geçen tüm güzel dilekler kabul olsun. Bu Cuma yüzünüz gülsün. Hayırlı Cumalar. 🌷",
  "Rahmet kapılarının ardına kadar açıldığı bu günde Rabbim sizi affetsin. Hayırlı Cumalar. 🕋",
  "Kalbi Allah sevgisiyle dolu olanlara ne mutlu. Bu Cuma huzur bulasınız. Hayırlı Cumalar. 💚",
  "Bugün Cuma; tövbelerin kabul, günahların aff, duaların makbul olduğu gün. Hayırlı Cumalar. 🤲",
  "Allah'ım! Bu Cuma hürmetine hastalarımıza şifa, dertlilere derman, dualarımıza kabul nasip eyle. Amin. 🕌",
  "Selam olsun imanla yaşayanlara, hayırlı Cumalar dileyenlere ve gönlü güzel insanlara. 🌙"
];

/* ══════════ İSLAMİ BİLGİ QUİZİ (50 Soru) ══════════ */
const QUIZ_QUESTIONS = [
  { q: "Kur'an-ı Kerim kaç sureden oluşur?", options: ["112", "114", "116", "120"], answer: 1 },
  { q: "İslam'ın ilk şartı nedir?", options: ["Namaz", "Oruç", "Kelime-i Şehadet", "Zekât"], answer: 2 },
  { q: "Günde kaç vakit namaz farzdır?", options: ["3", "4", "5", "6"], answer: 2 },
  { q: "Ramazan ayında tutulan oruç hangi namazdan sonra açılır (iftar)?", options: ["Öğle", "İkindi", "Akşam", "Yatsı"], answer: 2 },
  { q: "Kur'an'ın ilk suresi hangisidir?", options: ["Bakara", "Fâtiha", "İhlâs", "Nâs"], answer: 1 },
  { q: "Kur'an'ın en uzun suresi hangisidir?", options: ["Bakara", "Âl-i İmran", "Nisâ", "Mâide"], answer: 0 },
  { q: "Peygamberimiz Hz. Muhammed (s.a.v.) hangi şehirde doğmuştur?", options: ["Medine", "Kudüs", "Mekke", "Taif"], answer: 2 },
  { q: "Kâbe hangi şehirdedir?", options: ["Medine", "Mekke", "Şam", "Bağdat"], answer: 1 },
  { q: "Zekât kaç oranında verilir?", options: ["%2,5", "%5", "%10", "%20"], answer: 0 },
  { q: "Hac ibadeti nerede yapılır?", options: ["Medine", "Mekke", "Kudüs", "Necef"], answer: 1 },
  { q: "İlk vahiy hangi ayla başlamıştır?", options: ["Recep", "Şaban", "Ramazan", "Muharrem"], answer: 2 },
  { q: "Namazda kıble neresidir?", options: ["Mescid-i Aksa", "Kâbe", "Mescid-i Nebevî", "Arafat"], answer: 1 },
  { q: "Peygamberimizin annesinin adı nedir?", options: ["Halime", "Âmine", "Hatice", "Fatıma"], answer: 1 },
  { q: "Peygamberimizin ilk eşi kimdir?", options: ["Âişe", "Hatice", "Hafsa", "Zeynep"], answer: 1 },
  { q: "Kur'an kaç yılda tamamlanmıştır (yaklaşık)?", options: ["10 yıl", "23 yıl", "30 yıl", "40 yıl"], answer: 1 },
  { q: "Hangisi meleklerdendir?", options: ["Cebrail", "Ebu Leheb", "Bilal", "Selman"], answer: 0 },
  { q: "Vahiy getiren melek hangisidir?", options: ["Mikail", "İsrafil", "Cebrail", "Azrail"], answer: 2 },
  { q: "Can alan melek hangisidir?", options: ["Cebrail", "Azrail", "Mikail", "İsrafil"], answer: 1 },
  { q: "Kur'an'ın 'kalbi' olarak bilinen sure hangisidir?", options: ["Yâsîn", "Mülk", "Rahmân", "Fetih"], answer: 0 },
  { q: "Sabah namazının farzı kaç rekâttır?", options: ["2", "3", "4", "5"], answer: 0 },
  { q: "Öğle namazının farzı kaç rekâttır?", options: ["2", "3", "4", "5"], answer: 2 },
  { q: "Akşam namazının farzı kaç rekâttır?", options: ["2", "3", "4", "5"], answer: 1 },
  { q: "İhlâs suresi kaç ayettir?", options: ["3", "4", "5", "6"], answer: 1 },
  { q: "Hangisi büyük meleklerden değildir?", options: ["Cebrail", "Mikail", "Harut", "İsrafil"], answer: 2 },
  { q: "Peygamberimizin dedesi kimdir?", options: ["Ebu Talib", "Abdulmuttalib", "Abdullah", "Hamza"], answer: 1 },
  { q: "İlk Müslüman erkek kimdir (büyükler arasında)?", options: ["Ömer", "Ebubekir", "Osman", "Ali"], answer: 1 },
  { q: "Hangi peygamber 'Halilullah' (Allah'ın dostu) lakabıyla anılır?", options: ["Musa", "İbrahim", "İsa", "Nuh"], answer: 1 },
  { q: "Balığın karnında dua eden peygamber kimdir?", options: ["Yunus", "Yusuf", "Eyyub", "Zekeriya"], answer: 0 },
  { q: "Gemi yapan ve tufandan kurtulan peygamber kimdir?", options: ["Nuh", "Hud", "Salih", "Lut"], answer: 0 },
  { q: "Hangisi abdesti bozar?", options: ["Gülmek (namaz dışı)", "Su içmek", "Tuvalete gitmek", "Konuşmak"], answer: 2 },
  { q: "Cuma namazı kimlere farzdır?", options: ["Kadınlara", "Çocuklara", "Akıllı-baliğ erkeklere", "Yolculara"], answer: 2 },
  { q: "Teravih namazı hangi ayda kılınır?", options: ["Şaban", "Ramazan", "Şevval", "Recep"], answer: 1 },
  { q: "Kur'an'da adı geçen tek kadın kimdir?", options: ["Âişe", "Meryem", "Hatice", "Fatıma"], answer: 1 },
  { q: "Namaz kılmak için abdest almak neyin şartıdır?", options: ["Sünnet", "Farz (şart)", "Vacip", "Müstehap"], answer: 1 },
  { q: "Hangisi haram aylardan biridir?", options: ["Şaban", "Muharrem", "Ramazan", "Şevval"], answer: 1 },
  { q: "Kurban Bayramı kaç gündür?", options: ["1", "2", "3", "4"], answer: 3 },
  { q: "Ramazan Bayramı kaç gündür?", options: ["1", "2", "3", "4"], answer: 2 },
  { q: "İslam'ın şartları kaç tanedir?", options: ["4", "5", "6", "7"], answer: 1 },
  { q: "İmanın şartları kaç tanedir?", options: ["4", "5", "6", "7"], answer: 2 },
  { q: "Kur'an-ı Kerim kaç cüzdür?", options: ["20", "30", "40", "60"], answer: 1 },
  { q: "Hangisi bir Kur'an suresidir?", options: ["Tevhid", "Kevser", "Salavat", "Tekbir"], answer: 1 },
  { q: "Miraç mucizesi hangi peygamberimize aittir?", options: ["Musa", "İsa", "Muhammed", "İbrahim"], answer: 2 },
  { q: "Peygamberimizin Mekke'den Medine'ye göçüne ne denir?", options: ["Miraç", "Hicret", "İsra", "Bedir"], answer: 1 },
  { q: "İlk cami hangisidir?", options: ["Mescid-i Nebevî", "Mescid-i Aksa", "Kâbe (Mescid-i Haram)", "Kuba"], answer: 2 },
  { q: "Namazda Fâtiha'dan sonra okunan sureye ne denir?", options: ["Zamm-ı sure", "Tekbir", "Kunut", "Tesbih"], answer: 0 },
  { q: "Oruç hangi durumda bozulmaz?", options: ["Bilerek yemek", "Su içmek", "Unutarak yemek", "Sigara içmek"], answer: 2 },
  { q: "Vitir namazı kaç rekâttır?", options: ["1", "2", "3", "4"], answer: 2 },
  { q: "Hangisi peygamberimizin torunudur?", options: ["Hamza", "Hasan", "Bilal", "Osman"], answer: 1 },
  { q: "Kelime-i Tevhid nasıl başlar?", options: ["Elhamdülillah", "Lâ ilâhe illallah", "Sübhanallah", "Allahu Ekber"], answer: 1 },
  { q: "Kur'an'ın son suresi hangisidir?", options: ["İhlâs", "Felâk", "Nâs", "Kevser"], answer: 2 }
];

/* ══════════ RÜYA TABİRLERİ (55 Tabir) ══════════ */
const RUYA_TABIRLERI = [
  { kw: "Su (Berrak)", meaning: "Berrak ve temiz su görmek; helal rızık, huzur, bereket ve hayırlı gelişmelere işaret eder." },
  { kw: "Su (Bulanık)", meaning: "Bulanık su; sıkıntı, üzüntü veya geçici bir zorluğa yorumlanır." },
  { kw: "Deniz", meaning: "Sakin deniz huzuru, dalgalı deniz ise hayattaki dalgalanmaları ve büyük fırsatları temsil eder." },
  { kw: "Yağmur", meaning: "Rahmet, bereket, bolluk ve gönül ferahlığına işaret eder." },
  { kw: "Ateş", meaning: "Kontrollü ateş güç ve enerjidir; zarar veren ateş fitne veya öfkeye işaret eder." },
  { kw: "Yılan", meaning: "Gizli düşman, mal veya rızık anlamına gelebilir; yılanı öldürmek düşmana galip gelmektir." },
  { kw: "Altın", meaning: "Kadınlar için hayır sayılsa da genelde erkekler için bazı yorumlarda sıkıntı ve endişe olarak geçer." },
  { kw: "Para", meaning: "Az para rızka, çok para bazen küçük sıkıntılara; para bulmak beklenmedik habere işaret eder." },
  { kw: "Ekmek", meaning: "Bereket, sağlıklı ve bol rızık, uzun ömür ve helal kazanca işaret eder." },
  { kw: "Bebek", meaning: "Yeni başlangıçlar, müjde, sevinç ve bereketli haberlere yorumlanır." },
  { kw: "Ölmek", meaning: "Uzun ömür, tövbe ve yeni bir hayata başlangıç olarak yorumlanır; genelde hayırdır." },
  { kw: "Ölü Görmek", meaning: "Vefat etmiş birini güler yüzlü görmek onun iyi halde olduğuna ve hayırlı habere işaret eder." },
  { kw: "Ağlamak", meaning: "Rüyada sessizce ağlamak sevince ve ferahlığa yorumlanır." },
  { kw: "Gülmek", meaning: "Aşırı gülmek bazı yorumlarda üzüntüye, tebessüm ise müjdeye işaret eder." },
  { kw: "Uçmak", meaning: "Yükselme, mevki, seyahat ve arzulara kavuşmaya işaret eder." },
  { kw: "Düşmek", meaning: "Yüksekten düşmek itibar kaybı veya bir işten vazgeçmeye yorumlanabilir." },
  { kw: "Ağaç", meaning: "Yeşil ağaç sağlıklı ve bereketli bir hayatı, meyveli ağaç bolluğu temsil eder." },
  { kw: "Meyve", meaning: "Mevsiminde meyve rızık ve kazanç; olgun meyve emeğin karşılığıdır." },
  { kw: "Çiçek", meaning: "Sevinç, güzellik, mutluluk ve hayırlı gelişmelere işaret eder." },
  { kw: "Kuş", meaning: "Güzel haber, müjde ve rızık; uçan kuş sürüsü bolluğa işaret eder." },
  { kw: "Balık", meaning: "Taze balık rızık ve ganimet, bol balık bereketli kazanca yorumlanır." },
  { kw: "At", meaning: "İzzet, şeref, yüksek mevki ve hayırlı işlere işaret eder." },
  { kw: "Ev", meaning: "Yeni ev huzur, güven ve aile saadetine; ev yıkılması sıkıntıya yorumlanır." },
  { kw: "Kâbe", meaning: "Hidayet, huzur, hac nasibi ve manevi yükselişe işaret eden çok hayırlı bir rüyadır." },
  { kw: "Namaz Kılmak", meaning: "İşlerin yoluna girmesi, dua kabulü ve manevi huzura işaret eder." },
  { kw: "Kur'an Okumak", meaning: "Hidayet, ilim, bereket ve gönül huzuruna yorumlanır; çok hayırlıdır." },
  { kw: "Ezan", meaning: "Hayra çağrı, müjde, hac veya hayırlı bir davete işaret eder." },
  { kw: "Cami", meaning: "Huzur, birlik, hayırlı işler ve manevi olgunluğa yorumlanır." },
  { kw: "Peygamber Görmek", meaning: "Çok büyük hayır, hidayet, bereket ve müjdedir." },
  { kw: "Nur / Işık", meaning: "Hidayet, ilim, iman ve gönül aydınlığına işaret eder." },
  { kw: "Güneş", meaning: "Devlet, itibar, güç ve baba figürünü temsil eder." },
  { kw: "Ay", meaning: "Güzellik, müjde, anne figürü ve yükselişe işaret eder." },
  { kw: "Yıldız", meaning: "Umut, hedefler ve önemli kişilerle tanışmaya yorumlanır." },
  { kw: "Süt", meaning: "Saf rızık, ilim, fıtrat ve bereketli kazanca işaret eder." },
  { kw: "Bal", meaning: "Şifa, ilim, helal ve tatlı kazanca yorumlanır." },
  { kw: "Diş (Düşmesi)", meaning: "Akraba ile ilgili haber veya bir sıkıntının geçmesine yorumlanabilir." },
  { kw: "Saç", meaning: "Uzun saç mal ve uzun ömür; saç kesmek sıkıntıdan kurtulmaya işaret eder." },
  { kw: "Kan", meaning: "Haram mal veya sıkıntı; bazı yorumlarda sıkıntıdan kurtuluşa işaret eder." },
  { kw: "Düğün", meaning: "Sevinçli bir olay veya bazen dikkat gerektiren bir habere yorumlanır." },
  { kw: "Gelin", meaning: "Yeni başlangıç, sevinç, dünya nimetleri ve fırsatlara işaret eder." },
  { kw: "Yol", meaning: "Düz yol doğruluğu, geniş yol kolaylığı, dar yol zorluğu temsil eder." },
  { kw: "Köprü", meaning: "Bir durumdan diğerine geçiş, engelleri aşmak ve hayırlı değişime işaret eder." },
  { kw: "Dağ", meaning: "Yüksek makam, güçlü kişi veya aşılması gereken bir hedefe yorumlanır." },
  { kw: "Yağ", meaning: "Bereket, rızık ve mal artışına işaret eder." },
  { kw: "Beyaz Elbise", meaning: "Temizlik, iyi hal, itibar ve hayırlı hallere işaret eder." },
  { kw: "Yüzük", meaning: "Erkek için güç ve mevki, kadın için evlilik ve mutluluğa yorumlanır." },
  { kw: "Anahtar", meaning: "Yeni fırsatlar, çözülen sorunlar ve hayırlı kapıların açılmasına işaret eder." },
  { kw: "Kitap", meaning: "İlim, hikmet, hidayet ve hayırlı haberlere yorumlanır." },
  { kw: "Bahçe", meaning: "Cennet misali güzellik, huzur, bereket ve mutlu bir hayata işaret eder." },
  { kw: "Deve", meaning: "Sabır, güçlü bir yolculuk, büyük kazanç veya miras anlamına gelir." },
  { kw: "Koyun", meaning: "Bereket, mal, helal rızık ve kurban ibadetine işaret eder." },
  { kw: "Arı", meaning: "Çalışkanlık, bereketli kazanç ve hayırlı bir topluluğa yorumlanır." },
  { kw: "Deprem", meaning: "Ani değişiklikler, korku veya toplumsal bir olaya işaret edebilir." },
  { kw: "Bulut", meaning: "Beyaz bulut rahmet ve müjde, kara bulut geçici sıkıntı olarak yorumlanır." },
  { kw: "Merdiven", meaning: "Yükselme, terfi, manevi ilerleme ve hedeflere ulaşmaya işaret eder." }
];

/* ══════════ BEBEK İSİMLERİ (110 İsim) ══════════ */
const BEBEK_ISIMLERI = [
  { name: "Ahmet", gender: "erkek", meaning: "En çok övülen, Hz. Muhammed'in isimlerinden biri." },
  { name: "Mehmet", gender: "erkek", meaning: "Muhammed isminin Türkçe söylenişi; övülmüş." },
  { name: "Mustafa", gender: "erkek", meaning: "Seçilmiş, arınmış; Peygamberimizin isimlerinden." },
  { name: "Ali", gender: "erkek", meaning: "Yüce, ulu, şerefli." },
  { name: "Ömer", gender: "erkek", meaning: "Uzun ömürlü, hayat dolu." },
  { name: "Osman", gender: "erkek", meaning: "Toy kuşu yavrusu; ashaptan bir sahabe adı." },
  { name: "Yusuf", gender: "erkek", meaning: "Allah'ın kat kat verdiği; bir peygamber adı." },
  { name: "İbrahim", gender: "erkek", meaning: "Halktan yüce, halkların babası; bir peygamber adı." },
  { name: "İsmail", gender: "erkek", meaning: "Allah işitti; bir peygamber adı." },
  { name: "Hamza", gender: "erkek", meaning: "Aslan, güçlü; Peygamberimizin amcası." },
  { name: "Emir", gender: "erkek", meaning: "Bey, komutan, yönetici." },
  { name: "Yunus", gender: "erkek", meaning: "Bir peygamber adı; deniz balığı." },
  { name: "Enes", gender: "erkek", meaning: "Cana yakın, dost, ünsiyet kuran." },
  { name: "Bilal", gender: "erkek", meaning: "Su ile ıslatan; İlk müezzin Bilal-i Habeşi." },
  { name: "Selim", gender: "erkek", meaning: "Sağlam, kusursuz, temiz kalpli." },
  { name: "Kerem", gender: "erkek", meaning: "Cömertlik, iyilik, asalet." },
  { name: "Yasin", gender: "erkek", meaning: "Kur'an'ın 36. suresi; 'Ey insan' anlamında." },
  { name: "Taha", gender: "erkek", meaning: "Kur'an'ın 20. suresi; Peygamberimize hitap." },
  { name: "Eymen", gender: "erkek", meaning: "Uğurlu, hayırlı, sağ taraftan olan." },
  { name: "Furkan", gender: "erkek", meaning: "Hak ile batılı ayıran; Kur'an'ın adlarından." },
  { name: "Kaan", gender: "erkek", meaning: "Hükümdar, hakan." },
  { name: "Poyraz", gender: "erkek", meaning: "Kuzeydoğudan esen serin rüzgar." },
  { name: "Aras", gender: "erkek", meaning: "Bir nehir adı; akarsu." },
  { name: "Miraç", gender: "erkek", meaning: "Yükseğe çıkma; Peygamberimizin göğe yükselişi." },
  { name: "Talha", gender: "erkek", meaning: "Cennette bir ağaç; cennetle müjdelenen sahabe." },
  { name: "Muhammed", gender: "erkek", meaning: "Övülmüş, hamd edilmiş; Peygamberimizin adı." },
  { name: "Halil", gender: "erkek", meaning: "Samimi dost; İbrahim peygamberin lakabı." },
  { name: "Salih", gender: "erkek", meaning: "İyi, dürüst, yararlı; bir peygamber adı." },
  { name: "Davut", gender: "erkek", meaning: "Sevgili; bir peygamber adı." },
  { name: "Süleyman", gender: "erkek", meaning: "Huzurlu, barış içinde; bir peygamber adı." },
  { name: "Harun", gender: "erkek", meaning: "Dağ gibi güçlü; bir peygamber adı." },
  { name: "Musa", gender: "erkek", meaning: "Sudan çıkarılan; bir peygamber adı." },
  { name: "İsa", gender: "erkek", meaning: "Kurtarıcı; bir peygamber adı." },
  { name: "Zekeriya", gender: "erkek", meaning: "Allah'ı çokça anan; bir peygamber adı." },
  { name: "Yahya", gender: "erkek", meaning: "Yaşayan, canlı; bir peygamber adı." },
  { name: "Eyüp", gender: "erkek", meaning: "Sabrın simgesi; bir peygamber adı." },
  { name: "Kuzey", gender: "erkek", meaning: "Dört ana yönden biri; serin ve güçlü." },
  { name: "Alp", gender: "erkek", meaning: "Yiğit, kahraman, cesur." },
  { name: "Arda", gender: "erkek", meaning: "İşaret, nişan; nesil, ardıl." },
  { name: "Toprak", gender: "erkek", meaning: "Bereketli, verimli; sabırlı ve mütevazı." },
  { name: "Efe", gender: "erkek", meaning: "Yiğit, mert, Ege'nin kabadayısı." },
  { name: "Ege", gender: "erkek", meaning: "Bir deniz adı; ferah ve engin." },
  { name: "Çınar", gender: "erkek", meaning: "Uzun ömürlü, güçlü ve heybetli bir ağaç." },
  { name: "Berat", gender: "erkek", meaning: "Nişan, ferman; günahlardan kurtuluş belgesi." },
  { name: "Ömer Faruk", gender: "erkek", meaning: "Hak ile batılı ayıran uzun ömürlü." },
  { name: "Ensar", gender: "erkek", meaning: "Yardımcılar; Medineli Müslümanlar." },
  { name: "Redvan", gender: "erkek", meaning: "Hoşnutluk; cennet meleklerinden birinin adı." },
  { name: "Sinan", gender: "erkek", meaning: "Mızrak ucu; keskin ve güçlü." },
  { name: "Kemal", gender: "erkek", meaning: "Olgunluk, mükemmellik, erdem." },
  { name: "Barış", gender: "erkek", meaning: "Huzur, sükûnet, uzlaşma." },
  { name: "Deniz", gender: "erkek", meaning: "Engin su kütlesi; ferahlık ve bereket." },
  { name: "Umut", gender: "erkek", meaning: "Beklenti, ümit, iyi günlere inanç." },
  { name: "Metehan", gender: "erkek", meaning: "Büyük Türk hükümdarı; kahraman." },
  { name: "Batuhan", gender: "erkek", meaning: "Güçlü hükümdar, sağlam han." },

  { name: "Zeynep", gender: "kiz", meaning: "Değerli taş, süs ağacı; Peygamberimizin kızı." },
  { name: "Fatma", gender: "kiz", meaning: "Sütten kesilen; Peygamberimizin kızı Fatıma." },
  { name: "Ayşe", gender: "kiz", meaning: "Yaşayan, hayat dolu; Peygamberimizin eşi." },
  { name: "Hatice", gender: "kiz", meaning: "Erken doğan; Peygamberimizin ilk eşi." },
  { name: "Elif", gender: "kiz", meaning: "Alfabenin ilk harfi; incelik ve zarafet." },
  { name: "Meryem", gender: "kiz", meaning: "İbadet eden; Hz. İsa'nın annesi." },
  { name: "Sümeyye", gender: "kiz", meaning: "İslam'ın ilk kadın şehidi." },
  { name: "Hafsa", gender: "kiz", meaning: "Aslan yavrusu; Peygamberimizin eşi." },
  { name: "Rukiye", gender: "kiz", meaning: "Yükselen, dua; Peygamberimizin kızı." },
  { name: "Esma", gender: "kiz", meaning: "İsimler, güzel adlar; ünlü bir sahabe adı." },
  { name: "Rana", gender: "kiz", meaning: "Göz alıcı, güzel, hoş görünüşlü." },
  { name: "Zehra", gender: "kiz", meaning: "Parlak, aydınlık; Fatıma'nın lakabı." },
  { name: "Beyza", gender: "kiz", meaning: "Bembeyaz, tertemiz, saf." },
  { name: "Büşra", gender: "kiz", meaning: "Müjde, sevindirici haber." },
  { name: "Kübra", gender: "kiz", meaning: "En büyük, ulu." },
  { name: "Sena", gender: "kiz", meaning: "Övgü, şükür, methetme." },
  { name: "Nisa", gender: "kiz", meaning: "Kadınlar; Kur'an'da bir sure adı." },
  { name: "Nur", gender: "kiz", meaning: "Işık, aydınlık, parlaklık." },
  { name: "Melek", gender: "kiz", meaning: "İyilik ve saflığın timsali; melek." },
  { name: "İkra", gender: "kiz", meaning: "Oku; ilk inen vahyin ilk kelimesi." },
  { name: "Sude", gender: "kiz", meaning: "Menfaat, fayda, huzur." },
  { name: "Defne", gender: "kiz", meaning: "Her mevsim yeşil kalan hoş kokulu ağaç." },
  { name: "Naz", gender: "kiz", meaning: "İşve, cilve, nazlılık." },
  { name: "Ela", gender: "kiz", meaning: "Sarıya çalan kahverengi göz rengi." },
  { name: "Duru", gender: "kiz", meaning: "Berrak, temiz, saf." },
  { name: "Ada", gender: "kiz", meaning: "Etrafı suyla çevrili kara parçası; huzur adası." },
  { name: "Ravza", gender: "kiz", meaning: "Cennet bahçesi; Peygamberimizin kabrinin bulunduğu yer." },
  { name: "Berra", gender: "kiz", meaning: "İyilik eden, hayırlı, itaatkâr." },
  { name: "Cemre", gender: "kiz", meaning: "Kışın sonuna doğru havaya düşen sıcaklık; ateş közü." },
  { name: "Eslem", gender: "kiz", meaning: "Kusursuz, en sağlam, teslim olan." },
  { name: "Feyza", gender: "kiz", meaning: "Bolluk, bereket, feyz." },
  { name: "Gökçe", gender: "kiz", meaning: "Gök rengi, mavi; güzel, sevimli." },
  { name: "Hira", gender: "kiz", meaning: "İlk vahyin geldiği mağaranın adı." },
  { name: "İrem", gender: "kiz", meaning: "Cennet bahçesi." },
  { name: "Kumsal", gender: "kiz", meaning: "Deniz kıyısındaki ince kum." },
  { name: "Lamia", gender: "kiz", meaning: "Parlayan, parıldayan." },
  { name: "Masal", gender: "kiz", meaning: "Hayal dünyası, güzel anlatı." },
  { name: "Nehir", gender: "kiz", meaning: "Akarsu; bereket ve süreklilik." },
  { name: "Öykü", gender: "kiz", meaning: "Hikâye, kısa anlatı." },
  { name: "Pınar", gender: "kiz", meaning: "Yerden kaynayan su, kaynak; berraklık." },
  { name: "Rüya", gender: "kiz", meaning: "Uykuda görülen düş; güzel hayaller." },
  { name: "Sıla", gender: "kiz", meaning: "Kavuşma, memlekete dönüş, birleşme." },
  { name: "Şevval", gender: "kiz", meaning: "Ramazan sonrası hicri ay; bayram ayı." },
  { name: "Tuana", gender: "kiz", meaning: "Cennette bir ırmak; Allah'ın nuru." },
  { name: "Yağmur", gender: "kiz", meaning: "Rahmet, bereket; gökten inen su." },
  { name: "Yaren", gender: "kiz", meaning: "Yakın dost, arkadaş, sırdaş." },
  { name: "Zülal", gender: "kiz", meaning: "Tatlı, saf ve berrak su." },
  { name: "Asel", gender: "kiz", meaning: "Bal; tatlılık ve şirinlik." },
  { name: "Berin", gender: "kiz", meaning: "En yüce, en yüksek." },
  { name: "Ceylin", gender: "kiz", meaning: "Cennet suyu, cennet ırmağı (Selsebil)." },
  { name: "Dilek", gender: "kiz", meaning: "İstek, arzu, temenni." },
  { name: "Hümeyra", gender: "kiz", meaning: "Beyaz tenli; Hz. Âişe'nin lakabı." },
  { name: "Vera", gender: "kiz", meaning: "Takva, günahtan sakınma, incelik." },
  { name: "Reyyan", gender: "kiz", meaning: "Cennetin oruç tutanlara ayrılan kapısı." },
  { name: "Amine", gender: "kiz", meaning: "Güvenilir, emin; Peygamberimizin annesi." }
];

